It is not necessary; webpack 5 is now default for all Next.js apps
From now on, enabling this option using `future` will throw an error:
```
Error: `future.webpack5` in `next.config.js` has moved to the top level `webpack5` flag https://nextjs.org/docs/messages/future-webpack5-moved-to-webpack5
    at loadWebpackHook (/home/kibe/projects/portfolio/node_modules/next/dist/next-server/server/config-utils.js:3:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async loadConfig (/home/kibe/projects/portfolio/node_modules/next/dist/next-server/server/config.js:7:558)
    at async NextServer.loadConfig (/home/kibe/projects/portfolio/node_modules/next/dist/server/next.js:1:3155)
    at async NextServer.prepare (/home/kibe/projects/portfolio/node_modules/next/dist/server/next.js:1:2679)
    at async /home/kibe/projects/portfolio/node_modules/next/dist/cli/next-dev.js:22:1
```

You could fix the error by removing the `feature` object; however, it's not even necessary since webpack 5 will be enabled by default.

More info here: https://nextjs.org/docs/messages/future-webpack5-moved-to-webpack5